# permissions for end users to view hephaestusdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hephaestusdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: hephaestusdeployment-viewer-role
rules:
- apiGroups:
  - operator.kubiki.amocna
  resources:
  - hephaestusdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kubiki.amocna
  resources:
  - hephaestusdeployments/status
  verbs:
  - get
