---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.kubiki.amocna
  resources:
  - hephaestusdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kubiki.amocna
  resources:
  - hephaestusdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kubiki.amocna
  resources:
  - hephaestusdeployments/status
  verbs:
  - get
  - patch
  - update
